openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Dont-Be-Last API"

security:
  - sharedSecretAuth: []

paths:
  /login:
    post:
      tags:
        - "Player"
      summary: Authenticate user
      requestBody:
        description: login details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: unauthorized 
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /games/:
    get:
      tags:
        - "Game"
      summary: Retrieve all games with player waiting
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameWaitingList'



  /games/{id}/state:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        description: unique game id
        required: true
        style: simple
    get:
      tags:
        - "Game"
      summary: Retrieve game state based on game id
      responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GameState'

  /games/{id}/move:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        description: unique game id
        required: true
        style: simple
    post:
      tags:
        - "Game"
      summary: Player move for the game id
      requestBody:
          description: login details
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoveRequest'
      responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GameState'

components:
  securitySchemes:
    sharedSecretAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    LoginRequest:
      type: object
      properties:
        username: 
          type: string
        password: 
          type: string

    GameWaitingList:
      type: object
      properties:
        games:
          type: array
          items:
            properties:
              id: 
                type: string
                description: game id
              player_name:
                type: string
                description: opponent player waiting

    GameState:
      type: object
      properties:
        board:
          $ref: '#/components/schemas/Board'
        players:
          type: object
          properties:
              own:
                $ref: '#/components/schemas/PlayerInfo'
              opponent:
                $ref: '#/components/schemas/PlayerInfo'

    Board:
      type: array
      items:
        properties:
          id:
            type: integer
            description: 0 -> inactive cell & 1 -> active cell

    PlayerInfo:
      type: object
      properties:
        id:
          type: integer
          description: player id
        name:
          type: string
          description: player name
        is_turn:
          type: boolean
          description: true -> player's turn
        is_winner:
          type: string
          description: true -> player won

    MoveRequest:
      type: object
      properties:
        moves:
          type: array
          items:
            properties:
              id:
                type: integer
                description: Index of the board's cell
